name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        cc: [ clang, gcc ]
        make: [ bmake, pmake ]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pmake bmake pcregrep

    - name: make
      run: ${{ matrix.make }} -r -j 2 PKGCONF=pkg-config CC=${{ matrix.cc }}

    - name: test
      # I don't want to build SID just for sake of its -l test
      run: ${{ matrix.make }} -r -j 2 PKGCONF=pkg-config SID='true; echo sid' CC=${{ matrix.cc }} LX=./build/bin/lx test

    - name: install
      run: ${{ matrix.make }} -r -j 2 PKGCONF=pkg-config PREFIX=/tmp/p install
